apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Values.config.argoNamespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ .Chart.Name }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          containers:
          - name: monitor
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: ARGO_NAMESPACE
              value: {{ .Values.config.argoNamespace | quote }}
            - name: MAX_RETRIES
              value: {{ .Values.config.maxRetries | quote }}
            - name: RETRY_INTERVAL
              value: {{ .Values.config.retryInterval | quote }}
            - name: PROGRESSING_TIMEOUT
              value: {{ .Values.config.progressingTimeout | quote }}
            - name: SLACK_WEBHOOK_URL
              value: {{ .Values.config.slackWebhookUrl | quote }}
            {{- if .Values.resources }}
            resources:
              {{- toYaml .Values.resources | nindent 18 }}
            {{- end }}
          restartPolicy: OnFailure
          {{- if .Values.rbac.create }}
          serviceAccountName: {{ .Values.rbac.serviceAccountName }}
          {{- end }}
