{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-rolebinding
  namespace: {{ .Values.config.argoNamespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ .Values.config.argoNamespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-{{ .Chart.Name }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
